---
- name: Create user
  ansible.builtin.user:
    name: borg
    home: /home/borg
    shell: /bin/bash

- name: Create path /var/backup
  ansible.builtin.file:
    path: /var/backup
    state: directory
    owner: borg
    group: borg

- name: Create new primery partition
  community.general.parted:
    device: /dev/sdb
    number: 1
    state: present
    part_end: 2GiB

- name: Create a ext4 filesystem on /dev/sdb1
  community.general.filesystem:
    fstype: ext2
    dev: /dev/sdb1

- name: Check UUID /dev/sdb1
  command: blkid /dev/sdb1 | sed 's/[^"]*"\([^"]*\).*/\1/'

- name: Mount device in /var/backup
  ansible.posix.mount:
    path: /var/backup
    src: 


