---
- name: Generate ssh key
  ansible.builtin.user:
    name: vagrant
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: view ssh key pub
  shell: cat /home/vagrant/.ssh/id_rsa.pub
  register: ssh_key_client

- name: input ssh key client in server file
  ansible.builtin.lineinfile:
    path: /home/borg/.ssh/authorized_keys
    line: '{{ssh_key_client}}' 
  delegate_to: server

